### ISSUE TITLE
Architecture Feedbacks

### ISSUE THREAD

**Issue by warnigo** [mtakhirov/website#1]
### I Have Some Feedback on the Architecture 🙃

In the current implementation, **pages** are placed in the `src/features/pages` directory, which does not align with the principles of a **feature-based structure**. **Pages** should not be part of _the features layer_, as they represent high-level UI components typically tied to routing and app-level logic. Instead, they should be located in the `src/app` directory or a similar high-level structure.

> [!TIP]
> If there is specific functionality or reusable components within a page that logically belong to a **feature** or **entity**, only those parts should be extracted and placed into the respective `features` or `entities` layer. This ensures adherence to architectural principles and maintains a clear separation of concerns. 😉

<img width="990" alt="Screenshot 2024-12-22 at 11 02 23" src="https://github.com/user-attachments/assets/e6560a6f-008e-4a85-a2c5-c0a967891cce" />

#### Fragments and Slices

It’s important to structure and use **fragments** within **slices** correctly. I noticed files like `types.ts` and `components.ts` inside some slices. However, according to FSD (Feature-Sliced Design) documentation, **slices should be organized into segments**.

Segments are essential for maintaining a clear and structured architecture. Note that only `app` and `shared` layers are considered global layers, so segments are not applicable to them.

**According to FSD principles, segments can include the following:**
  <img width="997" alt="Screenshot 2024-12-22 at 10 51 38" src="https://github.com/user-attachments/assets/b9ee4626-8135-488d-8468-5c3ca25caa15" />

Adhering to these guidelines helps ensure a clean, user-friendly, and scalable architecture.

**Comment by warnigo** [comment]
### Important Point to Consider When Naming Segments

<img width="957" alt="Screenshot 2024-12-22 at 11 04 53" src="https://github.com/user-attachments/assets/ae002df5-5f87-41a7-b8be-3a3fc7131a73" />

**Comment by mtakhirov** [comment]
**Thank you for the detailed feedback and valuable insights regarding the architecture! I appreciate the time and effort you put into highlighting areas of improvement. 😊**

### **Routing**

Regarding the page components previously located in `src/features/pages`, I completely agree with your observation. I also found this placement odd and misaligned with best practices. In the new architecture, these components have been moved to the `views` directory, and the `app` directory has undergone refactoring to better reflect its purpose.

The `app` directory has been refactored. The folder structure now looks like this:
```
app/
├── (routes)/
│   ├── (homepage)/
│   │   ├── page.tsx # <- Homepage ["/"]
│   ├── about/
│   │   ├── page.tsx # <- About page ["/about"]
├── layouts/
│   ├── root-layout.tsx
│   ├── base-layout.tsx
│   ├── index.ts
├── config.ts
├── index.ts
```

### **Fragments and Segments:**

For fragments and segments, I initially intended to consolidate **_types_**, **_hooks_**, and **_helper functions_** into shared directories, which slightly deviated from **_FSD principles_**. However, your feedback made me reconsider this approach. I have now created a dedicated segment folder for **_hooks/helpers_** and named files according to their functionality. These are exported via the segment’s **index** file.

Type interfaces are now included within the slice layer's **index** file, unless they are intended for global use.
Example:
```
widgets/
├── header/
│   ├── config/
│   │   ├── index.ts # <- Shared configuration
│   ├── hook/
│   │   ├── use-header-scroll.tsx # <- `useHeaderScroll` hook
│   │   ├── index.ts
│   ├── widget.tsx # <- `HeaderWidget` component
│   ├── index.ts
```

### **The updated architecture:** 

The updated architecture is available in the [architecture](https://github.com/mtakhirov/website/tree/architecture) branch.

**I would love to hear your thoughts on this new structure as well. Thank you once again for your valuable input! 😊**
